### ISSUE TITLE
Adding Terminalizer format

### ISSUE THREAD

**Issue by faressoft** [stayradiated/terminal.sexy#52]
I am the owner of [Terminalizer](https://github.com/faressoft/terminalizer).

I am searching for a tool that helps my users to convert colors schemas into my format

Is it possible to support the following format so I can put a link in my repo about your service.

```
# Theme
theme:
  background: "#1B1D1E"
  foreground: "#6F6F6F"
  cursor: "#6F6F6F"
  black: "#1B1D1E"
  red: "#E6DC44"
  green: "#C8BE46"
  yellow: "#F4FD22"
  blue: "#737174"
  magenta: "#747271"
  cyan: "#62605F"
  white: "#C6C5BF"
  brightBlack: "#505354"
  brightRed: "#FFF78E"
  brightGreen: "#FFF27D"
  brightYellow: "#FEED6C"
  brightBlue: "#919495"
  brightMagenta: "#747271"
  brightCyan: "#A3A3A6"
  brightWhite: "#DADBD6"
```
