### ISSUE TITLE
[Feature Request] Ability to export color themes to Warp terminal format

### ISSUE THREAD

**Issue by dannyneira** [stayradiated/terminal.sexy#84]
I'm a Support Engineer at www.warp.dev which is a modern terminal that has a very similar export format to Alacritty. Warp also supports background images in the terminal, but if it's possible, it would be great if terminal.sexy users could at least export the color scheme to Warps yaml format. You can learn more about the format here: https://docs.warp.dev/appearance/custom-themes#create-your-own-custom-theme-manually

Along with an example below:

```
accent: '#268bd2' # Accent color for UI elements
background: '#002b36' # Terminal background color
details: darker # Whether the theme is lighter or darker.
foreground: '#839496' # The foreground color.
terminal_colors: # Ansi escape colors.
  bright:
    black: '#002b36'
    blue: '#839496'
    cyan: '#93a1a1'
    green: '#586e75'
    magenta: '#6c71c4'
    red: '#cb4b16'
    white: '#fdf6e3'
    yellow: '#657b83'
  normal:
    black: '#073642'
    blue: '#268bd2'
    cyan: '#2aa198'
    green: '#859900'
    magenta: '#d33682'
    red: '#dc322f'
    white: '#eee8d5'
    yellow: **'#b58900'**
```

We'd be happy to help with co-promotion and/or publishing on the site terminal.sexy's ability to export to Warp.
